# Import Library

In [2]:
import tensorflow as tf
import numpy as np

# Membuat sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [3]:
rdm_tensor = tf.random.normal([5,5], mean=0., stddev=1., seed=1) #membuat tensor menggunakan tf.random.normal
rdm_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

# Membuat sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [4]:
list_bilprim = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

bilprim_tensor = tf.constant(list_bilprim, dtype=tf.float32) #membuat tensor menggunakan tf.constant
bilprim_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

# Menampilkan dimensi dari kedua variable tersebut

In [5]:
rdm_tensor.shape #menampilkan dimensi dari variabel rdm_tensor menggunakan perintah shape

TensorShape([5, 5])

In [6]:
bilprim_tensor.shape #menampilkan dimensi dari variabel bilprim_tensor menggunakan perintah shape

TensorShape([5, 5])

# Menampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [7]:
print("Penjumlahan :",tf.add(bilprim_tensor,rdm_tensor)) #perhitungan aritmetika penjumlahan menggunakan tf.add

Penjumlahan : tf.Tensor(
[[ 1.1886818  4.4845986  5.0653296  4.557296  11.099248 ]
 [13.591225  17.592823  16.877071  22.277103  28.94373  ]
 [31.643545  36.735676  42.856632  43.56784   46.617165 ]
 [51.514656  60.261772  60.974693  70.73537   74.532814 ]
 [77.25702   82.5621    88.43399   97.32067    2.132831 ]], shape=(5, 5), dtype=float32)


In [8]:
print("Pengurangan :",tf.subtract(bilprim_tensor,rdm_tensor)) #perhitungan aritmetika penjumlahan menggunakan tf.subtract


Pengurangan : tf.Tensor(
[[ 2.8113182   1.5154012   4.9346704   9.442704   10.900752  ]
 [12.408775   16.407177   21.122929   23.722897   29.05627   ]
 [30.356455   37.264324   39.143368   42.43216    47.382835  ]
 [54.485344   57.738228   61.025307   71.26463    71.467186  ]
 [80.74298    83.4379     89.56601    96.67933    -0.13283098]], shape=(5, 5), dtype=float32)


In [9]:
print("Perkalian :",tf.multiply(bilprim_tensor,rdm_tensor)) #perhitungan aritmetika penjumlahan menggunakan tf.multiply

Perkalian : tf.Tensor(
[[  -1.6226364     4.4537964     0.32664686  -17.09893       1.0917324 ]
 [   7.685916     10.077991    -40.335663    -16.626637     -1.6318411 ]
 [  19.949888     -9.77999      76.12196      24.417194    -17.993286  ]
 [ -78.7232       74.444496     -1.5436709   -18.788708    111.89541   ]
 [-137.69519     -36.345116    -50.37489      31.10492       1.132831  ]], shape=(5, 5), dtype=float32)


In [10]:
print("Pembagian :",tf.divide(bilprim_tensor,rdm_tensor)) #perhitungan aritmetika penjumlahan menggunakan tf.divide

Pembagian : tf.Tensor(
[[-2.46512389e+00  2.02074814e+00  7.65352554e+01 -2.86567640e+00
   1.10833015e+02]
 [ 2.19882698e+01  2.86763515e+01 -8.94989681e+00 -3.18164177e+01
  -5.15368835e+02]
 [ 4.81706963e+01 -1.39979691e+02  2.20829830e+01  7.57253265e+01
  -1.22768005e+02]
 [-3.56819878e+01  4.67596703e+01 -2.41048804e+03 -2.68299438e+02
   4.76248322e+01]
 [-4.53247490e+01 -1.89544052e+02 -1.57241043e+02  3.02492340e+02
   8.82744193e-01]], shape=(5, 5), dtype=float32)


In [11]:
print("Pangkat :",tf.pow(bilprim_tensor,rdm_tensor)) #perhitungan aritmetika penjumlahan menggunakan tf.pow

Pangkat : tf.Tensor(
[[5.6986094e-01 5.1089730e+00 1.1108701e+00 8.6233392e-03 1.2686931e+00]
 [4.5560699e+00 5.3633776e+00 1.9288398e-03 1.0365988e-01 8.2739007e-01]
 [9.1150293e+00 3.8502288e-01 9.8707019e+02 8.4635296e+00 2.2901341e-01]
 [2.7469979e-03 1.7155756e+02 9.0119815e-01 3.2366973e-01 7.1800415e+02]
 [4.9258291e-04 1.4442728e-01 7.8818068e-02 4.3360734e+00 1.0000000e+00]], shape=(5, 5), dtype=float32)


# Menampilkan nilai maksimal dan minimal dari variable random_tensor

In [12]:
tf.argmax(rdm_tensor, axis=1). numpy() #menampilkan nilai max dari kolom(axis=1) variabel rdm_tensor

array([1, 1, 2, 4, 4], dtype=int64)

In [19]:
tf.argmin(rdm_tensor, axis=1). numpy() #menampilkan nilai min dari kolom(axis=1) variabel rdm_tensor

array([4, 4, 1, 0, 2], dtype=int64)

In [22]:
tf.argmax(rdm_tensor, axis=0). numpy() #menampilkan nilai max dari baris(axis=0) variabel rdm_tensor

array([2, 0, 2, 2, 3], dtype=int64)

In [25]:
tf.argmin(rdm_tensor, axis=0). numpy() #menampilkan nilai min dari baris(axis=0) variabel rdm_tensor

array([4, 4, 1, 0, 2], dtype=int64)

# Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [14]:
tf.concat([rdm_tensor, bilprim_tensor], axis=1) #penggabungan kolom dari 2 variabel menggunakan tf.concat 

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0000000e+00]], dtype=float32)>

In [26]:
tf.concat([rdm_tensor, bilprim_tensor], axis=0) #penggabungan baris dari 2 variabel menggunakan tf.concat 

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
      

# Menampilkan hasil sorting dari kedua variable di atas. (descending)

In [15]:
#sorting dari variabel rdm_tensor secara descending menggunakan tf.sort dan direction(perintah sorting) : descending
sort_rdm_tensor1 = tf.sort(rdm_tensor, direction="DESCENDING") 
sort_rdm_tensor1.numpy()

array([[ 1.4845988 ,  0.0992484 ,  0.06532937, -0.8113182 , -2.4427042 ],
       [ 0.59282297,  0.5912243 , -0.05627038, -0.72289723, -2.1229296 ],
       [ 1.8566332 ,  0.6435448 ,  0.5678417 , -0.26432407, -0.3828359 ],
       [ 1.5328138 ,  1.2617711 , -0.02530608, -0.2646297 , -1.4853433 ],
       [ 1.132831  ,  0.32066926, -0.43789294, -0.56601   , -1.7429771 ]],
      dtype=float32)

In [16]:
#sorting dari variabel bilprim_tensor secara descending menggunakan tf.sort dan direction(perintah sorting) : descending
sort_bilprim_tensor1 = tf.sort(bilprim_tensor, direction="DESCENDING")
sort_bilprim_tensor1.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)

In [17]:
#variabel rdm_tensor
#sorting secara descending menggunakan direction(perintah sorting) dan tf.argsort():Mengembalikan index dari tensornya
sort_rdm_tensor2 = tf.argsort(rdm_tensor, direction="DESCENDING") 
sort_rdm_tensor2.numpy()

array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])

In [18]:
#variabel bilprim_tensor
#sorting secara descending menggunakan direction(perintah sorting) dan tf.argsort():Mengembalikan index dari tensornya
sort_bilprim_tensor2 = tf.argsort(bilprim_tensor, direction="DESCENDING")
sort_bilprim_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])